# Name of your application. Used to uniquely configure containers.
service: puntospoint

# Name of the container image.
image: caliwa/puntospoint

# Deploy to these servers.
servers:
  web:
    - 206.189.226.103
  options:
      network: 'private'
  
  job:
    hosts:
      - 206.189.226.103
    cmd: bundle exec sidekiq -q default -q mailers
    options:
      network: 'private'

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
proxy:
  ssl: true
  host: rubicon-prog.online

# Credentials for your image host.
registry:
  username: caliwa
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    # Database configuration para Rails
    DB_HOST: 206.189.226.103
    DB_PORT: 5432
    DB_NAME: puntospoint_production
    DB_USER: puntospoint
    # Redis configuration
    REDIS_HOST: 206.189.226.103
    REDIS_PORT: 6379
  secret:
    - RAILS_MASTER_KEY
    - DB_PASSWORD
    - REDIS_URL

# Use a persistent storage volume.
volumes:
  - "puntospoint_storage:/app/storage"

# Use accessory services (secrets come from .kamal/secrets).
accessories:
  db:
    image: postgres:16
    host: 206.189.226.103
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'puntospoint'
        POSTGRES_DB: 'puntospoint_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    options:
      network: 'private'
  
  redis:
    image: redis:7.0
    host: 206.189.226.103
    port: 6379
    directories:
      - data:/data
    options:
      network: 'private'