# Name of your application. Used to uniquely configure containers.
service: puntospoint

# Name of the container image.
image: caliwa/puntospoint

# Deploy to these servers.
servers:
  web:
    hosts:
      - 134.199.199.203
    options:
      network: 'private'
  
  job:
    hosts:
      - 134.199.199.203
    cmd: bundle exec sidekiq -q default -q mailers
    options:
      network: 'private'

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
proxy:
  ssl: true
  host: rubicon-prog.online
  app_port: 3000

# Credentials for your image host.
registry:
  username: caliwa
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  cache:
    type: registry
    options: mode=max

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    # Database configuration para Rails
    POSTGRES_DB: 'puntospoint_production'
    POSTGRES_USER: 'puntospoint'
    POSTGRES_HOST: 'puntospoint-db'
    # Redis configuration
    REDIS_URL: 'redis://puntospoint-redis:6379/0'
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD


# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a persistent storage volume.
volumes:
  - "puntospoint_storage:/app/storage"

# Use accessory services (secrets come from .kamal/secrets).
accessories:
  db:
    image: postgres:16
    host: 134.199.199.203
    env:
      clear:
        POSTGRES_USER: 'puntospoint'
        POSTGRES_DB: 'puntospoint_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    options:
      network: 'private'
  
  redis:
    image: redis:7.0
    host: 134.199.199.203
    directories:
      - data:/data
    options:
      network: 'private'