name: Deploy to Production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    env:
      DOCKER_BUILDKIT: 1
      RAILS_ENV: production
      BUNDLE_WITHOUT: "development test"
      BUNDLE_WITH: tools

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up SSH and add key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
        run: |
          set -e
          echo "Starting SSH setup..."
          # Start the ssh-agent
          eval $(ssh-agent -s)
          
          # Create a temporary file for the key
          KEY_FILE_PATH=$(mktemp)
          
          # Write the secret to the temporary file and ensure it ends with a newline
          echo "${SSH_PRIVATE_KEY}" > "${KEY_FILE_PATH}"
          
          # Ensure correct permissions on the key file
          chmod 600 "${KEY_FILE_PATH}"
          
          # Add the key to the agent
          ssh-add "${KEY_FILE_PATH}"
          
          echo "SSH key added to agent."
          
          # Create .ssh directory
          mkdir -p ~/.ssh
          
          # Scan the host key and add it to known_hosts
          ssh-keyscan 206.189.226.103 >> ~/.ssh/known_hosts
          
          echo "Host key for 206.189.226.103 added to known_hosts."

      - name: Deploy with Kamal
        run: bin/kamal deploy
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
